### Get
GET {{url}}/v1/greetings/Dinesh
Content-Type: application/json


### Get Courses
GET {{url}}/v1/courses
Content-Type: application/json


### Create new course
POST {{url}}/v1/courses
Content-Type: application/json

{
  "name": "Java1",
  "category": "Tech"
}

### Modify
PUT {{url}}/tables/1
Content-Type: application/json

{
  "name": "costa-rica",
  "seatCount": 10,
  "active": true
}

### Get all
GET {{url}}/tables

### Get single
GET {{url}}/tables/3000

### Delete
DELETE {{url}}/tables/1